### ISSUE TITLE
freefilesync dont compile on my gentoo

### ISSUE THREAD

**Issue by sdelanoue** [mbucas/gentoo-overlay#1]
Hi Wen installing freefilesync on my gentoo systemd-mergedusr I got several warning in Cpp compilation but as the warning are considered as error the build actually fail
here are the attached information on my gentoo build

[emergeinfo.txt](https://github.com/mbucas/gentoo-overlay/files/14406737/emergeinfo.txt)
[emergepvq.txt](https://github.com/mbucas/gentoo-overlay/files/14406739/emergepvq.txt)
[build.log](https://github.com/mbucas/gentoo-overlay/files/14406742/build.log)
 fell free to ask more if needed
regards
Stéphane

**Comment by mbucas** [comment]
Thanks for reporting this.
When I created the ebuild for 12.4, it wasn't ready because it needed OpenSSL 3.0. Now I see that there were other problems.

I've updated to FreeFileSync version 13.0, it compiles and I can synchronize folders, but some dialogs don't always show up. I type Esc and get back to the main window.

Can you try this version and tell me if it's better ?

Best regards
Mickaël

**Comment by mbucas** [comment]
As they say, _works for me_
Feel free to reopen if needed !
